name: bebo_auto_service
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  hexcolor: ^3.0.1
  onboarding: ^3.1.0
  smooth_page_indicator: ^1.1.0
  social_login_buttons: ^1.0.7
  flutter_social_button: ^1.1.4+1
  conditional_builder_null_safety: ^0.0.6
  awesome_snackbar_content: ^0.1.3
  email_validator: ^2.1.17
  page_transition: ^2.0.9
  dio: ^5.2.1+1
  fluttertoast: ^8.2.2
  bottom_bar_matu: ^1.3.0
  fluentui_system_icons: ^1.1.202
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  lottie: ^2.3.1
  like_button: ^2.0.5
  flutter_switch: ^0.3.2
  loading_animation_widget: ^1.2.0+4
  badges: ^3.1.1
  readmore: ^2.2.0
  flutter_custom_clippers: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.0.1
  image_cropper: ^4.0.1
  restart_app: ^1.1.2
  photo_view: ^0.14.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  emoji_picker_flutter: ^1.6.1
  swipe_to: ^1.0.2
  scrollable_positioned_list: ^0.3.8
  flutter_material_color_picker: ^1.1.0
  shimmer: ^3.0.0
  google_fonts: ^4.0.0
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  countup: ^0.1.4
  dropdown_button2: ^2.3.9

  #firebase
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.7
  firebase_performance: ^0.9.3+4

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: ^2.1.1
  custom_clippers: ^2.0.0
  connectivity_plus: ^4.0.2
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  transparent_image: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  gallery_saver: ^2.3.2
  flutter_native_splash: ^2.3.5
  url_launcher: ^6.2.1
  sleek_circular_slider: ^2.0.1
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#232121"
  color_dark: "#232121"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  ios : true
  android_12:
    image: assets/images/logo.png
    color_dark: "#232121"
    color: "#232121"
    image_dark: assets/images/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/icons/
    - assets/part_categories_grid.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf


    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf


    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

    - family: SevenSegment
      fonts:
        - asset: assets/fonts/SevenSegment.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
