// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOz0KcIwer6rBEsS9Z06eaZLeLts5GLzA',
    appId: '1:707769663992:web:188ffe3094dfddf2c0560d',
    messagingSenderId: '707769663992',
    projectId: 'bebo-auto-service',
    authDomain: 'bebo-auto-service.firebaseapp.com',
    storageBucket: 'bebo-auto-service.appspot.com',
    measurementId: 'G-GE1LVNF7GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJiibFYA8v3Slr4Q8A83Y398ybfIsDA8',
    appId: '1:707769663992:android:407ecb56919f7922c0560d',
    messagingSenderId: '707769663992',
    projectId: 'bebo-auto-service',
    storageBucket: 'bebo-auto-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjBBnfsCvnuTtmrW55o-LDCwuBJhhMEE',
    appId: '1:707769663992:ios:cb2b8c46ce5b549dc0560d',
    messagingSenderId: '707769663992',
    projectId: 'bebo-auto-service',
    storageBucket: 'bebo-auto-service.appspot.com',
    iosBundleId: 'com.example.beboAutoService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjBBnfsCvnuTtmrW55o-LDCwuBJhhMEE',
    appId: '1:707769663992:ios:6701de322410ca29c0560d',
    messagingSenderId: '707769663992',
    projectId: 'bebo-auto-service',
    storageBucket: 'bebo-auto-service.appspot.com',
    iosBundleId: 'com.example.beboAutoService.RunnerTests',
  );
}
